use utils::GenericError;

fn main() -> Result<(),GenericError> {
    
   

    Ok(())
}

